services:
  # Mongo
  - type: web
    name: mongo
    env: docker
    dockerContext: .
    dockerfilePath: ./docker/Dockerfile.mongo
    rootDir: .
    plan: free
    # disk:
    #   name: mongo-data
    #   mountPath: /data/db
    #   sizeGB: 10
    envVars:
      - key: PORT
        sync: 27017
      # - key: MONGO_URL
      #   value: MONGO_URL
      - fromGroup: microrealestate
    region: oregon

  # Gateway
  - type: web
    name: gateway
    env: docker
    dockerContext: .
    dockerfilePath: ./services/gateway/Dockerfile
    plan: free
    envVars:
      - key: NODE_OPTIONS
        value: --trace-warnings
      - key: CORS_ENABLED
        sync: false
      - key: DOMAIN_URL
        sync: false
      - key: EXPOSE_FRONTENDS
        value: true
      - key: LOGGER_LEVEL
        sync: false
      - key: MONGO_URL
        sync: false
      - key: PRODUCTION
        value: true
      - key: REDIS_URL
        sync: false
      # - key: RESETSERVICE_URL
      #   value: ${RESETSERVICE_URL}
      - key: PORT
        value: 8080
      - key: GATEWAY_DEBUG_PORT
        sync: false
      - fromGroup: microrealestate
    region: oregon

  # Authenticator
  - type: web
    name: authenticator
    env: docker
    dockerContext: .
    dockerfilePath: ./services/authenticator/Dockerfile
    plan: free
    envVars:
      - key: NODE_OPTIONS
        value: --trace-warnings
      - key: EMAILER_URL
        sync: false
      - key: LOGGER_LEVEL
        sync: false
      - key: MONGO_URL
        sync: false
      - key: PORT
        value: 8000
      - key: PRODUCTION
        value: true
      - key: REDIS_URL
        sync: false
      - key: SIGNUP
        value: false
      - key: TOKEN_COOKIE_ATTRIBUTES
        sync: false
      - key: AUTHENTICATOR_DEBUG_PORT
        sync: false
      - fromGroup: microrealestate
    region: oregon

  # PDFGenerator
  - type: web
    name: pdfgenerator
    env: docker
    dockerContext: .
    dockerfilePath: ./services/pdfgenerator/Dockerfile
    plan: free
    envVars:
      - key: NODE_OPTIONS
        value: --trace-warnings
      - key: CHROMIUM_BIN
        sync: false
      - key: DATA_DIRECTORY
        sync: false
      - key: LOGGER_LEVEL
        sync: false
      - key: MONGO_URL
        sync: false
      - key: PDF_DIRECTORY
        sync: false
      - key: PORT
        value: 8300
      - key: PRODUCTION
        value: true
      - key: REDIS_URL
        sync: false
      - key: TEMPLATES_DIRECTORY
        sync: false
      - key: TEMPORARY_DIRECTORY
        sync: false
      - key: UPLOAD_MAX_SIZE
        sync: false
      - key: UPLOADS_DIRECTORY
        sync: false
      - key: PDFGENERATOR_DEBUG_PORT
        sync: false
      - fromGroup: microrealestate
    region: oregon

  # Emailer
  - type: web
    name: emailer
    env: docker
    dockerContext: .
    dockerfilePath: ./services/emailer/Dockerfile
    plan: free
    envVars:
      - key: NODE_OPTIONS
        value: --trace-warnings
      - key: ALLOW_SENDING_EMAILS
        sync: false
      - key: APP_NAME
        sync: false
      - key: CIPHER_IV_KEY
        sync: false
      - key: CIPHER_KEY
        sync: false
      - key: LANDLORD_APP_URL
        sync: false
      - key: LOGGER_LEVEL
        sync: false
      - key: MONGO_URL
        sync: false
      - key: PDFGENERATOR_URL
        sync: false
      - key: PORT
        value: 8400
      - key: PRODUCTION
        value: true
      - key: REDIS_PASSWORD
        sync: false
      - key: REDIS_URL
        sync: false
      - key: TEMPORARY_DIRECTORY
        sync: false
      - key: TENANT_APP_URL
        sync: false
      - key: EMAILER_DEBUG_PORT
        sync: false
      - fromGroup: microrealestate
    region: oregon

  # API
  - type: web
    name: api
    env: docker
    dockerContext: .
    dockerfilePath: ./services/api/Dockerfile
    plan: free
    envVars:
      - key: NODE_OPTIONS
        value: --trace-warnings
      - key: PORT
        value: API_PORT
      - key: API_DEBUG_PORT
        value: API_DEBUG_PORT
      - fromGroup: microrealestate
    region: oregon

  # TenantAPI
  - type: web
    name: tenantapi
    env: docker
    dockerContext: .
    dockerfilePath: ./services/tenantapi/Dockerfile
    plan: free
    envVars:
      - key: NODE_OPTIONS
        value: --trace-warnings
      - key: PORT
        value: TENANTAPI_PORT
      - key: TENANTAPI_DEBUG_PORT
        value: TENANTAPI_DEBUG_PORT
      - fromGroup: microrealestate
    region: oregon

  # Landlord Frontend
  - type: web
    name: landlord-frontend
    env: docker
    dockerContext: .
    dockerfilePath: ./webapps/landlord/Dockerfile
    plan: free
    envVars:
      - key: PORT
        value: LANDLORD_FRONTEND_PORT
      - fromGroup: microrealestate
    region: oregon

  # Tenant Frontend
  - type: web
    name: tenant-frontend
    env: docker
    dockerContext: ./webapps/tenant/
    dockerfilePath: ./webapps/tenant/dev.Dockerfile
    rootDir: .
    buildCommand: docker build -t tenant-frontend -f webapps/tenant/dev.Dockerfile --build-arg BASE_PATH=$TENANT_BASE_PATH .
    plan: free
    envVars:
      - key: PORT
        value: ${TENANT_FRONTEND_PORT}
    region: oregon
