services:
  # Mongo
  - type: web
    name: mongo
    env: docker
    dockerContext: .
    dockerfilePath: ./docker/Dockerfile.mongo
    rootDir: .
    plan: free
    # disk:
    #   name: mongo-data
    #   mountPath: /data/db
    #   sizeGB: 10
    envVars:
      - key: PORT
        value: MONGO_PORT
      # - key: MONGO_URL
      #   value: MONGO_URL
      - fromGroup: microrealestate
    region: oregon

  # Gateway
  - type: web
    name: gateway
    env: docker
    dockerContext: .
    dockerfilePath: ./services/gateway/Dockerfile
    plan: free
    envVars:
      - key: NODE_OPTIONS
        value: --trace-warnings
      - key: CORS_ENABLED
        value: CORS_ENABLED
      - key: DOMAIN_URL
        value: DOMAIN_URL
      - key: EXPOSE_FRONTENDS
        value: true
      - key: LOGGER_LEVEL
        value: LOGGER_LEVEL
      - key: MONGO_URL
        value: MONGO_URL
      - key: PRODUCTION
        value: true
      - key: REDIS_URL
        value: REDIS_URL
      # - key: RESETSERVICE_URL
      #   value: ${RESETSERVICE_URL}
      - key: PORT
        value: GATEWAY_PORT
      - key: GATEWAY_DEBUG_PORT
        value: GATEWAY_DEBUG_PORT
      - fromGroup: microrealestate
    region: oregon

  # Authenticator
  - type: web
    name: authenticator
    env: docker
    dockerContext: .
    dockerfilePath: ./services/authenticator/Dockerfile
    plan: free
    envVars:
      - key: NODE_OPTIONS
        value: --trace-warnings
      - key: EMAILER_URL
        value: EMAILER_URL
      - key: LOGGER_LEVEL
        value: LOGGER_LEVEL
      - key: MONGO_URL
        value: MONGO_URL
      - key: PORT
        value: AUTHENTICATOR_PORT
      - key: PRODUCTION
        value: true
      - key: REDIS_URL
        value: REDIS_URL
      - key: SIGNUP
        value: false
      - key: TOKEN_COOKIE_ATTRIBUTES
        value: TOKEN_COOKIE_ATTRIBUTES
      - key: AUTHENTICATOR_DEBUG_PORT
        value: AUTHENTICATOR_DEBUG_PORT
      - fromGroup: microrealestate
    region: oregon

  # PDFGenerator
  - type: web
    name: pdfgenerator
    env: docker
    dockerContext: .
    dockerfilePath: ./services/pdfgenerator/Dockerfile
    plan: free
    envVars:
      - key: NODE_OPTIONS
        value: --trace-warnings
      - key: CHROMIUM_BIN
        value: CHROMIUM_BIN
      - key: DATA_DIRECTORY
        value: DATA_DIRECTORY
      - key: LOGGER_LEVEL
        value: LOGGER_LEVEL
      - key: MONGO_URL
        value: MONGO_URL
      - key: PDF_DIRECTORY
        value: PDF_DIRECTORY
      - key: PORT
        value: PDFGENERATOR_PORT
      - key: PRODUCTION
        value: true
      - key: REDIS_URL
        value: REDIS_URL
      - key: TEMPLATES_DIRECTORY
        value: TEMPLATES_DIRECTORY
      - key: TEMPORARY_DIRECTORY
        value: TEMPORARY_DIRECTORY
      - key: UPLOAD_MAX_SIZE
        value: UPLOAD_MAX_SIZE
      - key: UPLOADS_DIRECTORY
        value: UPLOADS_DIRECTORY
      - key: PDFGENERATOR_DEBUG_PORT
        value: PDFGENERATOR_DEBUG_PORT
      - fromGroup: microrealestate
    region: oregon

  # Emailer
  - type: web
    name: emailer
    env: docker
    dockerContext: .
    dockerfilePath: ./services/emailer/Dockerfile
    plan: free
    envVars:
      - key: NODE_OPTIONS
        value: --trace-warnings
      - key: PORT
        value: EMAILER_PORT
      - key: EMAILER_DEBUG_PORT
        value: EMAILER_DEBUG_PORT
      - fromGroup: microrealestate
    region: oregon

  # API
  - type: web
    name: api
    env: docker
    dockerContext: .
    dockerfilePath: ./services/api/Dockerfile
    plan: free
    envVars:
      - key: NODE_OPTIONS
        value: --trace-warnings
      - key: PORT
        value: API_PORT
      - key: API_DEBUG_PORT
        value: API_DEBUG_PORT
      - fromGroup: microrealestate
    region: oregon

  # TenantAPI
  - type: web
    name: tenantapi
    env: docker
    dockerContext: .
    dockerfilePath: ./services/tenantapi/Dockerfile
    plan: free
    envVars:
      - key: NODE_OPTIONS
        value: --trace-warnings
      - key: PORT
        value: TENANTAPI_PORT
      - key: TENANTAPI_DEBUG_PORT
        value: TENANTAPI_DEBUG_PORT
      - fromGroup: microrealestate
    region: oregon

  # Landlord Frontend
  - type: web
    name: landlord-frontend
    env: docker
    dockerContext: .
    dockerfilePath: ./webapps/landlord/Dockerfile
    plan: free
    envVars:
      - key: PORT
        value: LANDLORD_FRONTEND_PORT
      - fromGroup: microrealestate
    region: oregon

  # Tenant Frontend
  - type: web
    name: tenant-frontend
    env: docker
    dockerContext: ./webapps/tenant/
    dockerfilePath: ./webapps/tenant/dev.Dockerfile
    rootDir: .
    buildCommand: docker build -t tenant-frontend -f webapps/tenant/dev.Dockerfile --build-arg BASE_PATH=$TENANT_BASE_PATH .
    plan: free
    envVars:
      - key: PORT
        value: ${TENANT_FRONTEND_PORT}
    region: oregon
