apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose --file ../docker-compose.microservices.base.yml convert -c
    kompose.version: 1.34.0 (HEAD)
  labels:
    app: api
  name: api
spec:
  ports:
    - name: "8200-8200"
      port: 8200
      targetPort: 8200
  selector:
    app: api
  type: ClusterIP
