apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose --file ../docker-compose.microservices.base.yml convert -c
    kompose.version: 1.34.0 (HEAD)
  labels:
    app: authenticator
  name: authenticator
spec:
  ports:
    - name: "8000-8000"
      port: 8000
      targetPort: 8000
  selector:
    app: authenticator
  type: ClusterIP
