apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose --file ../docker-compose.microservices.base.yml convert -c
    kompose.version: 1.34.0 (HEAD)
  labels:
    app: emailer
  name: emailer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: emailer
  template:
    metadata:
      annotations:
        kompose.cmd: kompose --file ../docker-compose.microservices.base.yml convert -c
        kompose.version: 1.34.0 (HEAD)
      labels:
        app: emailer
    spec:
      containers:
        - env:
            - name: ACCESS_TOKEN_SECRET
              value: "8126d047374a1fbf247064638770504f4cf42b57aa565992116d039c2c4fb7cf78bdf4bce7f409d130d787b67fbc4265cddad7f6697b193d0e4941981d0d45cb"
            - name: PORT
              value: "8400"
            - name: NODE_OPTIONS
              value: "--trace-warnings"
            - name: ALLOW_SENDING_EMAILS
              value: "true"
            - name: APP_NAME
              value: "Bomatech"
            - name: CIPHER_IV_KEY
              value: "e62d3774d57565718912a2fda32c30b86d4320ab483e41f739951130ad48c482"
            - name: CIPHER_KEY
              value: "4f9078a9c90d6e30d24400373734db3988758f773ae4f0b9b0d773aefe8c3dc6"
            - name: LANDLORD_APP_URL
              value: "http://landlord-frontend:8180/landlord"
            - name: LOGGER_LEVEL
              value: "debug"
            - name: MONGO_URL
              value: "mongodb+srv://bomatech:0NRcStqJS70trojB@bomatech-cluster.0eu6m.mongodb.net/bomatechTest?retryWrites=true&w=majority&appName=Bomatech-Cluster"
            - name: PDFGENERATOR_URL
              value: "http://pdfgenerator:8300/pdfgenerator"
            - name: REDIS_PASSWORD
              value: "12264d724d371d79054887f65175aa3758d89dbc7a05ab54cdb3d8c47df3aace47ee415904a7f3229e6714263ae35ab24caa7a6861eba09bbbf23c5871daf850"
            - name: REDIS_URL
              value: "redis://redis"
            # - name: TEMPORARY_DIRECTORY
            #   value: "/usr/app/services/pdfgenerator/tmp"
            - name: TENANT_APP_URL
              value: "http://tenant-frontend:8190/tenant"
            - name: EMAILER_DEBUG_PORT
              value: "9228"
            - name: NODE_ENV
              value: "production"
            - name: MAILGUN_API_KEY
              value: "a1623c62f79df30be16028e4a52cd61f-1b5736a5-f61ddecb"
            - name: MAILGUN_DOMAIN
              value: "sandbox53348a1c56bc4fc2ab89a724c3c57747.mailgun.org"
            - name: EMAIL_FROM
              value: "mailgun@sandbox53348a1c56bc4fc2ab89a724c3c57747.mailgun.org"
            - name: EMAIL_REPLY_TO
              value: "mailgun@sandbox53348a1c56bc4fc2ab89a724c3c57747.mailgun.org"
            - name: EMAIL_BCC
              value: "almbolonzi@gmail.com"
          image: almbolonzi/bomatech-emailer:latest
          name: emailer
          ports:
            - containerPort: 8400
              protocol: TCP
      restartPolicy: Always
