apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose --file ../docker-compose.microservices.base.yml convert -c
    kompose.version: 1.34.0 (HEAD)
  labels:
    app: landlord-frontend
  name: landlord-frontend
spec:
  ports:
    - name: "8180-8180"
      port: 8180
      targetPort: 8180
  selector:
    app: landlord-frontend
  type: ClusterIP
