apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose --file ../docker-compose.microservices.base.yml convert -c
    kompose.version: 1.34.0 (HEAD)
  labels:
    app: paymentprocessor
  name: paymentprocessor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: paymentprocessor
  template:
    metadata:
      annotations:
        kompose.cmd: kompose --file ../docker-compose.microservices.base.yml convert -c
        kompose.version: 1.34.0 (HEAD)
      labels:
        app: paymentprocessor
    spec:
      containers:
        - env:
            - name: ACCESS_TOKEN_SECRET
              value: "8126d047374a1fbf247064638770504f4cf42b57aa565992116d039c2c4fb7cf78bdf4bce7f409d130d787b67fbc4265cddad7f6697b193d0e4941981d0d45cb"
            - name: PORT
              value: "8001"
            - name: LOGGER_LEVEL
              value: "debug"
            - name: MONGO_URL
              value: "mongodb+srv://bomatech:0NRcStqJS70trojB@bomatech-cluster.0eu6m.mongodb.net/bomatechTest?retryWrites=true&w=majority&appName=Bomatech-Cluster"
            - name: PRODUCTION
              value: "true"
            - name: REDIS_URL
              value: "redis://redis"
            - name: REDIS_PASSWORD
              value: "12264d724d371d79054887f65175aa3758d89dbc7a05ab54cdb3d8c47df3aace47ee415904a7f3229e6714263ae35ab24caa7a6861eba09bbbf23c5871daf850"
            - name: UPLOAD_MAX_SIZE
              value: "2000000000"
            - name: NODE_ENV
              value: "production"
          image: ghcr.io/alex-mbolonzi/microrealestate/paymentprocessor:latest
          name: paymentprocessor
          ports:
            - containerPort: 8001
              protocol: TCP
      restartPolicy: Always
