apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose --file ../docker-compose.microservices.base.yml convert -c
    kompose.version: 1.34.0 (HEAD)
  labels:
    app: paymentprocessor
  name: paymentprocessor
spec:
  ports:
    - name: "8001"
      port: 8001
      targetPort: 8001
  selector:
    app: paymentprocessor
