apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose --file ../docker-compose.microservices.base.yml convert -c
    kompose.version: 1.34.0 (HEAD)
  labels:
    app: pdfgenerator
  name: pdfgenerator
spec:
  ports:
    - name: "8300-8300"
      port: 8300
      targetPort: 8300
  selector:
    app: pdfgenerator
  type: ClusterIP
