apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose --file ../docker-compose.microservices.base.yml convert -c
    kompose.version: 1.34.0 (HEAD)
  labels:
    app: pdfgenerator
  name: pdfgenerator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pdfgenerator
  template:
    metadata:
      annotations:
        kompose.cmd: kompose --file ../docker-compose.microservices.base.yml convert -c
        kompose.version: 1.34.0 (HEAD)
      labels:
        app: pdfgenerator
    spec:
      containers:
        - env:
            - name: ACCESS_TOKEN_SECRET
              value: "8126d047374a1fbf247064638770504f4cf42b57aa565992116d039c2c4fb7cf78bdf4bce7f409d130d787b67fbc4265cddad7f6697b193d0e4941981d0d45cb"
            - name: PORT
              value: "8300"
            - name: NODE_OPTIONS
              value: "--trace-warnings"
            - name: CHROMIUM_BIN
              value: "/usr/bin/chromium-browser"
            - name: DATA_DIRECTORY
              value: "/usr/app/services/pdfgenerator/data"
            - name: LOGGER_LEVEL
              value: "debug"
            - name: MONGO_URL
              value: "mongodb+srv://bomatech:0NRcStqJS70trojB@bomatech-cluster.0eu6m.mongodb.net/bomatechTest?retryWrites=true&w=majority&appName=Bomatech-Cluster"
            - name: PDF_DIRECTORY
              value: "/usr/app/services/pdfgenerator/pdf_documents"
            - name: PRODUCTION
              value: "true"
            - name: REDIS_URL
              value: "redis://redis"
            - name: REDIS_PASSWORD
              value: "12264d724d371d79054887f65175aa3758d89dbc7a05ab54cdb3d8c47df3aace47ee415904a7f3229e6714263ae35ab24caa7a6861eba09bbbf23c5871daf850"
            - name: TEMPLATES_DIRECTORY
              value: "/usr/app/services/pdfgenerator/templates"
            - name: TEMPORARY_DIRECTORY
              value: "/usr/app/services/pdfgenerator/tmp"
            - name: UPLOAD_MAX_SIZE
              value: "2000000000"
            - name: UPLOADS_DIRECTORY
              value: "/usr/app/services/pdfgenerator/uploads"
            - name: PDFGENERATOR_DEBUG_PORT
              value: "9227"
            - name: NODE_ENV
              value: "production"
            - name: CIPHER_IV_KEY
              value: "e62d3774d57565718912a2fda32c30b86d4320ab483e41f739951130ad48c482"
            - name: CIPHER_KEY
              value: "4f9078a9c90d6e30d24400373734db3988758f773ae4f0b9b0d773aefe8c3dc6"
          image: ghcr.io/alex-mbolonzi/microrealestate/pdfgenerator:d88630553c216b9abbae70ec6ae4bd58fcf91341
          name: pdfgenerator
          ports:
            - containerPort: 8300
              protocol: TCP
      restartPolicy: Always
