apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose --file ../docker-compose.microservices.base.yml convert -c
    kompose.version: 1.34.0 (HEAD)
  labels:
    app: tenantapi
  name: tenantapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tenantapi
  template:
    metadata:
      annotations:
        kompose.cmd: kompose --file ../docker-compose.microservices.base.yml convert -c
        kompose.version: 1.34.0 (HEAD)
      labels:
        app: tenantapi
    spec:
      containers:
        - env:
            - name: ACCESS_TOKEN_SECRET
              value: "8126d047374a1fbf247064638770504f4cf42b57aa565992116d039c2c4fb7cf78bdf4bce7f409d130d787b67fbc4265cddad7f6697b193d0e4941981d0d45cb"
            - name: PORT
              value: "8250"
            - name: NODE_OPTIONS
              value: "--trace-warnings"
            - name: CIPHER_IV_KEY
              value: "e62d3774d57565718912a2fda32c30b86d4320ab483e41f739951130ad48c482"
            - name: CIPHER_KEY
              value: "4f9078a9c90d6e30d24400373734db3988758f773ae4f0b9b0d773aefe8c3dc6"
            - name: DEMO_MODE
              value: "false"
            - name: LOGGER_LEVEL
              value: "debug"
            - name: MONGO_URL
              value: "mongodb://mongo/demodb"
            - name: TENANTAPI_DEBUG_PORT
              value: "9240"
            - name: NODE_ENV
              value: "production"
          image: ghcr.io/microrealestate/microrealestate/tenantapi:latest
          name: tenantapi
          ports:
            - containerPort: 8250
              protocol: TCP
      restartPolicy: Always
