apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose --file ../docker-compose.microservices.base.yml convert -c
    kompose.version: 1.34.0 (HEAD)
  labels:
    app: tenant-frontend
  name: tenant-frontend
spec:
  ports:
    - name: "8190-8190"
      port: 8190
      targetPort: 8190
  selector:
    app: tenant-frontend
  type: ClusterIP
