apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose --file ../docker-compose.microservices.base.yml convert -c
    kompose.version: 1.34.0 (HEAD)
  labels:
    app: tenant-frontend
  name: tenant-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tenant-frontend
  template:
    metadata:
      annotations:
        kompose.cmd: kompose --file ../docker-compose.microservices.base.yml convert -c
        kompose.version: 1.34.0 (HEAD)
      labels:
        app: tenant-frontend
    spec:
      containers:
        - env:
            - name: BASE_PATH
              value: "/tenant"
            - name: PORT
              value: "8190"
            - name: DOCKER_GATEWAY_URL
              value: "http://34.133.214.175:8080"
            - name: APP_NAME
              value: "Bomatech"
            - name: CORS_ENABLED
              value: "false"
            - name: DEMO_MODE
              value: "false"
            - name: GATEWAY_URL
              value: "http://34.133.214.175:8080"
            - name: NODE_ENV
              value: "production"
            - name: DOMAIN_URL
              value: "https://34.133.214.175:8080"
          image: ghcr.io/microrealestate/microrealestate/tenant-frontend:latest
          name: tenant-frontend
          ports:
            - containerPort: 8190
              protocol: TCP
      restartPolicy: Always
